INSERT INTO constant VALUES(default, 'Plastics XI');

-- Opposition
INSERT INTO opposition VALUES(default,'Hendricks XI');
INSERT INTO opposition VALUES(default,'Cumnor Challengers');
INSERT INTO opposition VALUES(default,'Princes Head CC');
INSERT INTO opposition VALUES(default,'Holtwhites Trinibis');
INSERT INTO opposition VALUES(default,'Kings Road');
INSERT INTO opposition VALUES(default,'Stanmore Warriors');
INSERT INTO opposition VALUES(default,'Roehampton CC');
INSERT INTO opposition VALUES(default,'Flying Ducksmen');
INSERT INTO opposition VALUES(default,'Railway Taverners');
INSERT INTO opposition VALUES(default,'Crossbats CC');
INSERT INTO opposition VALUES(default,'Southbank CC');
INSERT INTO opposition VALUES(default,'Graces');
INSERT INTO opposition VALUES(default,'Clapham CC');
INSERT INTO opposition VALUES(default,'Camel CC');
INSERT INTO opposition VALUES(default,'Egham Roses');
INSERT INTO opposition VALUES(default,'Gentlemen of West London');
INSERT INTO opposition VALUES(default,'Norwood Exiles');
INSERT INTO opposition VALUES(default,'Woodside Green');
INSERT INTO opposition VALUES(default,'Cincinnati CC');
INSERT INTO opposition VALUES(default,'Winchmore Hill Tigers');
INSERT INTO opposition VALUES(default,'Merton Boars');
INSERT INTO opposition VALUES(default,'Old Minchendenians');
INSERT INTO opposition VALUES(default,'Mavericks CC');

-- Members as of 12-05-2019
INSERT INTO player VALUES(default,'Saril',null,null,null,'Saril',1,null,null);
INSERT INTO player VALUES(default,'Jamie',null,'Doy',null,'J Doy',2,null,null);
INSERT INTO player VALUES(default,'Robert',null,'Bishop',null,'R Bishop',3,null,null);
INSERT INTO player VALUES(default,'Charlie',null,'Bradbury',null,'C Bradbury',4,null,null);
INSERT INTO player VALUES(default,'Matt',null,'Webb',null,'M Webb',5,null,null);
INSERT INTO player VALUES(default,'Mark',null,'Davies',null,'M Davies',6,null,null);
INSERT INTO player VALUES(default,'Peter',null,'Oliver',null,'P Oliver',7,null,null);
INSERT INTO player VALUES(default,'Mike',null,'Winter',null,'M Winter',8,null,null);
INSERT INTO player VALUES(default,'Niall',null,'Jackson',null,'N Jackson',9,null,null);
INSERT INTO player VALUES(default,'Henry',null,'Hobbs',null,'H Hobbs',10,null,null);
INSERT INTO player VALUES(default,'James',null,'Sandham',null,'J Sandham',11,null,null);
INSERT INTO player VALUES(default,'Maithri',null,'Jayasuriya',null,'M Jayasuriya',12,null,null);
INSERT INTO player VALUES(default,'Alex',null,'Webster',null,'A Webster',13,null,null);
INSERT INTO player VALUES(default,'Joey',null,'Anderson',null,'J Anderson',14,null,null);
INSERT INTO player VALUES(default,'Leo',null,'Bearcroft',null,'L Bearcroft',15,null,null);
INSERT INTO player VALUES(default,'Jerry',null,'Jamieson',null,'J Jamieson',16,null,null);
INSERT INTO player VALUES(default,'Simon',null,'Freeman',null,'S Freeman',17,null,null);
INSERT INTO player VALUES(default,'Pete',null,'Bishop',null,'P Bishop',18,null,null);
INSERT INTO player VALUES(default,'Tom',null,'Morgan-Grenville',null,'T Morgan-Grenville',19,null,null);
INSERT INTO player VALUES(default,'Tom',null,'Scott-Coombes',null,'T Scott-Coombes',20,null,null);
INSERT INTO player VALUES(default,'John',null,'Papadopoulos',null,'J Papadopoulos',21,null,null);
INSERT INTO player VALUES(default,'Dom',null,'Gillan',null,'D Gillan',22,null,null);
INSERT INTO player VALUES(default,'Anthony',null,'Mortimer',null,'A Mortimer',23,null,null);
INSERT INTO player VALUES(default,'Phil',null,'Byrne',null,'P Byrne',24,null,null);
INSERT INTO player VALUES(default,'James',null,'Dewhirst',null,'J Dewhirst',25,null,null);

-- Ringers
INSERT INTO player VALUES(default,'James',null,'Heis',null,'J Heis',null,null,null);
INSERT INTO player VALUES(default,'Billy',null,'Soomro',null,'B Soomro',null,null,null);
INSERT INTO player VALUES(default,'Alex',null,'Armytage',null,'A Armytage',null,null,null);
INSERT INTO player VALUES(default,'Jon',null,'Thornhill',null,'J Thornhill',null,null,null);
INSERT INTO player VALUES(default,'Liam',null,'Killen',null,'L Killen',null,null,null);
INSERT INTO player VALUES(default,'Ali',null,'Nurmohammed',null,'A Nurmohammed',null,null,null);
INSERT INTO player VALUES(default,'Saj',null,'Ali',null,'S Ali',null,null,null);
INSERT INTO player VALUES(default,'Michael',null,'Lizut',null,'M Lizut',null,null,null);
INSERT INTO player VALUES(default,'Mike',null,'Wills',null,'M Wills',null,null,null);
INSERT INTO player VALUES(default,'Hughie',null,'Jamieson',null,'H Jamieson',null,null,null);
INSERT INTO player VALUES(default,'Iain',null,'Gordon',null,'I Gordon',null,null,null);
INSERT INTO player VALUES(default,'James',null,'Jarvis',null,'J Jarvis',null,null,null);
INSERT INTO player VALUES(default,'Ian',null,'Whitfield',null,'I Whitfield',null,null,null);
INSERT INTO player VALUES(default,'Akhil',null,'Dogar',null,'A Dogar',null,null,null);
INSERT INTO player VALUES(default,'Avi',null,'Asthana',null,'A Asthana',null,null,null);
INSERT INTO player VALUES(default,'James',null,'Hewlett',null,'J Hewlett',null,null,null);
INSERT INTO player VALUES(default,'Neil',null,'Whitfield',null,'N Whitfield',null,null,null);
INSERT INTO player VALUES(default,'Rich',null,'Wills',null,'R Wills',null,null,null);